### ISSUE TITLE
White text on a white background

### ISSUE THREAD

**Issue by mic140** [zedlabs/ElementHistoryDialog#6]
Some elements are not visible in the dark theme in the History window, as there is white text on a white background
![Screenshot_2022-06-09-08-31-40-906_de blau android](https://user-images.githubusercontent.com/69987154/172774385-fa28f925-2a0b-4740-8b4f-0af57eb171bf.jpg)
![Screenshot_2022-06-09-08-42-57-921_de blau android](https://user-images.githubusercontent.com/69987154/172774437-046acdc5-6bfa-4594-aa55-e24f01bcd6ec.jpg)

**Comment by zedlabs** [comment]
hi thanks for the report, will look into this

**Comment by zedlabs** [comment]
Hi @mic140 this should be fixed in the latest release (1.0.4)

**Comment by mic140** [comment]
When will this fix appear in Vespucci?

**Comment by simonpoole** [comment]
This isn't resolved. The problem is that Vespucci has two distinctive themes that are independent of night mode, a light and a dark one. 

Changing colors in night mode will not have an effect on this problem. The IMHO easiest way to fix this is to allow passing of a style as a parameter, see https://github.com/simonpoole/OpeningHoursFragment/blob/master/lib/src/main/java/ch/poole/openinghoursfragment/OpeningHoursFragment.java#L194 and https://github.com/simonpoole/OpeningHoursFragment/blob/master/lib/src/main/java/ch/poole/openinghoursfragment/OpeningHoursFragment.java#L438, and then trying to avoid setting colors directly.

Update: the PR I created simply uses the themes primary color for background instead of using a hardwired value.
